[package]
edition = "2021"
name = "affect-api"
version = "0.1.0"

[dependencies]
prost = "0.9"
prost-types = "0.9"
tonic = { git = "https://github.com/hyperium/tonic.git", rev = "01e5be5" }

[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic.git", rev = "01e5be5" }
